apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-config-external-secret
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-config
    template:
      engineVersion: v2
      data:
        KC_HOSTNAME: "https://account.${CLUSTER_DOMAIN}"
        KC_HOSTNAME_ADMIN: "https://keycloak.${CLUSTER_DOMAIN}"
        KC_DB_USERNAME: "{{ .username }}"
        KC_DB_PASSWORD: "{{ .password }}"
        KC_DB: "postgres"
        KC_DB_URL_HOST: "cnpg-cluster-rw.cnpg-system.svc.cluster.local"
        KC_DB_URL_DATABASE: "keycloak"
  data:
  - secretKey: username # key in Kubernetes Secret
    remoteRef:
      key: keycloak-db-credentials # key in the secret store
      property: username # property in the secret store secret
  - secretKey: password # key in Kubernetes Secret
    remoteRef:
      key: keycloak-db-credentials # key in the secret store
      property: password # property in the secret store secret
