apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-server-env-external-secret
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: woodpecker-server-env
  dataFrom:
  - extract:
      key: woodpecker-server-env