apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-smtp-config-external-secret
  namespace: kube-prometheus-stack
spec:
  refreshInterval: 720h # 1 month
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: grafana-smtp-config
  data:
  - secretKey: smtp_host
    remoteRef:
      key: grafana-smtp-config
      property: smtp_host
  - secretKey: smtp_user
    remoteRef:
      key: grafana-smtp-config
      property: smtp_user
  - secretKey: smtp_password
    remoteRef:
      key: grafana-smtp-config
      property: smtp_password