apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-grafana-client-credentials-external-secret
  namespace: kube-prometheus-stack
spec:
  refreshInterval: 720h # 1 month
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-grafana-client-credentials
  data:
  - secretKey: client_id # key in Kubernetes Secret
    remoteRef:
      key: keycloak-grafana-client-credentials # key in the secret store
      property: client_id # property in the secret store secret
  - secretKey: client_secret # key in Kubernetes Secret
    remoteRef:
      key: keycloak-grafana-client-credentials # key in the secret store
      property: client_secret # property in the secret store secret