apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-db-credentials-external-secret
  namespace: cnpg-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: harbor-db-credentials
  data:
  - secretKey: username # key in Kubernetes Secret
    remoteRef:
      key: harbor-db-credentials # key in the secret store
      property: username # property in the secret store secret
  - secretKey: password # key in Kubernetes Secret
    remoteRef:
      key: harbor-db-credentials # key in the secret store
      property: password # property in the secret store secret