apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbao-ingress
  namespace: openbao
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-traefik-middleware-redirect-https@kubernetescrd,kube-system-traefik-middleware-hq-ipallowlist@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: openbao.${CLUSTER_DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: openbao
                port:
                  number: 8200
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - openbao.${CLUSTER_DOMAIN}
      secretName: openbao.${CLUSTER_DOMAIN}-tls