apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tcp-haproxy
  namespace: tcp-proxy
  labels:
    app: tcp-haproxy
spec:
  selector:
    matchLabels:
      app: tcp-haproxy
  template:
    metadata:
      labels:
        app: tcp-haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:2.8-alpine
          ports:
            - name: health
              containerPort: 8405
              protocol: TCP
            - name: forgejo-ssh
              containerPort: 32222
              hostPort: 32222
              protocol: TCP
            - name: postgresql
              containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8405
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8405
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-cfg-configmap
